### ISSUE TITLE
Why both the text of the GPL and the LGPL?

### ISSUE THREAD

**Issue by kozross** [netmail-open/wjelement#50]
This makes it unclear what license this is being offered under. By the text of your README, I assume that you mean the LGPL, but it'd be nice to make it clear.

**Comment by penduin** [comment]
Yes, our license is LGPL, any version.  (Important since v3 has some requirements not everybody likes.)  One of the LGPL's provisions is that you may also opt to use the GPL when creating derived works.  I don't know whether it's _required_ to provide both texts, but it's encouraged and common to do so.

We've also been quite permissive when it comes to static linking and stuff like that (for those who want to use WJE on iOS etc) but I have those licenses checked in to encourage a share-alike ecosystem.

It may be that in the future we'll allow/encourage use under additional licenses as well.  (Apache's license is a strong contender, for example.)  I'd like to know your (and anyone else's) opinion: is it more flexible/helpful to have multiple license choices, or is it only more confusing?  :^)

**Comment by kozross** [comment]
I'm a strong copyleft advocate, which basically means that I would prefer that you leave your licensing model as-is. Given that the LGPLv2 (which is permitted) is actually fairly permissive as far as copyleft licensing goes (and I believe that Apple's crusade is fundamentally against the GPLv3 due to patent provisions), I'd say 'don't change a thing'. Thanks for clarifying, though!

**Comment by penduin** [comment]
Cool.  I'll keep all this in mind and see if I can't make the wiki and/or other docs more clear.  Thanks!
