### ISSUE TITLE
Graceful malloc failure handling and/or memory optimization for constrained environments

### ISSUE THREAD

**Issue by mkarlesky** [netmail-open/wjelement#58]
Thank you for the library. It _may_ be just what we need for a project on an (embedded) AVR platform. We're specifically interested in the schema validation feature for validating some relatively simple JSON blobs.

I'm having trouble figuring out what I presume is a memory allocation problem.

We have a pretty capable build environment in which we can run unit tests on our production AVR code natively (OS X and Linux) and build some code libraries for all three platforms. I was able to strip down wjelement (removed 64 bit support, etc.) and add missing functionality (`strndup()`) such that the library would build both for AVR release and our native testing environments.

I have been successful in using the slimmed down library to validate JSON in our native test environment. Now I'm working to see if wjelement will run on our AVR chip. At first everything died when I put validation calls in our existing code. I soon figured out that it was because of memory allocation issues.

The default internal memory allocation is for 4k RAM in `WJROpenDocument()`, but we only have 8k RAM total!

I tweaked `_WJEParse()` to take a buffer allocation size value as a parameter. With that change and smaller memory allocation calls to `_WJEParse()` for a test JSON blob and a schema string both parsing calls now succeed. Unfortunately, the firmware crashes upon trying to validate the JSON blob against the schema. I assume this is more memory allocation issues.

1. What kind of memory optimization might I be able to do in the guts of `WJESchemaValidate()`? Is it even worth trying? I'm hoping there's more memory blocks whose default sizes I can cut down.
2. Could you direct me on how to change the code to more gracefully error out if memory allocation fails so I can track down the issue and robustify validation for our use case?

Anything you can say is very much appreciated.

**Comment by penduin** [comment]
Wow!  Sounds like you've done some great work and are using WJE in a very
awesome way!  :^)

Schema validation is memory-hungry in that it needs both the schema and
data documents open, but there might be some clever things that could
squeeze it into 8k. Depending on just how small and predictable your json
is, you might be better off doing a handful of checks rather than hacking
on WJESchemaValidate, but let me take a look and see if anything jumps out
at me as a good candidate for slimming down.

Worth noting: schema validation leverages regex for a handful of things,
which I assume you are not including.  It recurses for each object/array
layer in the document and the schema, and in 8k stack space could get tight
in a hurry.  There is support for drafts 3 and 4, which overlap a lot, but
whichever you're not using might mean some chunks can be axed.

Like I say, I'll take a look and see if i can come up with some more
concrete suggestions.  Best of luck, and I hope WJE ends up working out for
you!

later,
-Owen

**Comment by mkarlesky** [comment]
Thanks for the quick response!

You are correct. We omitted regex support. And, indeed, our JSON blobs are quite simple and predictable.

We're not using any advanced features of the schema draft—just simple verification that keys and values exist / are required with some min and max checks. That said, trying to do that checking “by hand” in code is proving to be quite tedious and difficult to maintain. The format checking is easily 70–80% of the JSON handling code we've written so far (thankfully, not much). Before we went further we decided to investigate a more general validation technique and were very happy to have found WJE (which also uses no advanced C++ features our release environment doesn't support).

We weren't quite sure how to go about wading through the draft 3 vs. 4 issue. If simple draft 4 support works in WJE (again, we have pretty simple JSON) then we'd be happy to use that as we're also looking at using schema validation in a much different environment elsewhere in this project. That library only supports draft 4. Consistency would be nice.

Any tricks you can think of to limit memory would be great. Incidentally, what are the implications of reducing the buffer size floor in `_WJROpenDocument()` I'm referring to this code and the logic before it: `buffersize = (sizeof(WJIReader) + 512)`?

**Comment by minego** [comment]
A smaller buffer for WJR should work just fine, but may cause issues with
the maximum name lengths and won't be as efficient. I haven't tried with a
small buffer for a long time but I'd say you will likely be okay to drop
that 512 down as low as 64.

Basically it needs a bit of room for a stack (1 character per depth in the
document), room for the name of the current element and a bit extra for
actual parsing.

If that is too small it will end up doing a lot of memmove() calls.

**Comment by penduin** [comment]
MemAsprintf is used a lot without result checking, so it would certainly be
worth adding checks and erroring out after those.  I think the biggest uses
of memory in the schema code are going to be the documents (json and
schema) themselves, and the stack used to navigate and examine them.
Unfortunately, I didn't spot any additional big bad default buffer sizes
for trimming.  :^)

Either/both WJESchemaValidate and ListSelectors could probably be reworked
to build up lists of pointers and work serially instead of recursing.  If
testing shows you're running out of stack, that might be worth the effort,
and would be kind of a fun exercise in a twisted way; I might need to take
a crack at that myself.  ;^)  The MemAsprintf stuff I mentioned is almost
entirely for building up selector strings used to look up and iterate
through certain children; it could be cheaper memory-wise to walk through
children directly.

I keep thinking, "this would be such small savings", but in the context of
working in 8k, these kinds of things might just be enough.  :^)

Would you mind sharing a sample json blob and schema, to illustrate what
you're working with?  As I mentioned, depending on how many schemas you use
and how often they change, it may be less dev time just to write a handful
of sanity checks manually, but I would take it as a point of pride if
WJESchema winds up being helpful in an 8k environment. :^)

later,
-Owen

**Comment by mkarlesky** [comment]
Ah yes. The unchecked `MemAsprintf()` would be fine in pretty much any environment larger than ours. I'll see if we can't tighten that up for more graceful failure. Do generic memory allocation (`malloc()` and its kin) generally get checked?

**In the meantime, I have some success to report!**

I've learned that I can, in fact, successfully parse JSON and a schema and validate them _**if**_ there are no arrays in the JSON string. To be clear, my little setup of nonsense JSON and a simple schema for it parsed successfully after I had previously tweaked wjelement buffer allocation. However, validation would go off into the weeds. By removing an array (of size 1) of simple objects in my testing JSON string, validation now succeeds.

So I'm guessing that the array of JSON object (singular—as there was only one) is tripping us over into recursion inside validation that is blowing up the stack? I should note that the schema only specifies top-level simple key/value pairs at present. I had cut out the specification for the array long ago as I tried to isolate the parsing and validation issues early on.

Does this tell us something useful? Thank you again!

**Comment by penduin** [comment]
There is probably other unchecked allocation code, but schema.c might be
the worst offender.  (My bad!)  In Netmail we use a custom "slabber" memory
allocator, which is why you'll see everything wrapped and/or macro'd as
Mem* calls.  At least that makes them all very easy to find!  :^)

If digging into array validation is dying, then my guess is you're right
and there's just no room left on the stack.  I am guessing
WJESchemaValidate may yield bigger savings than ListSelectors by having it
loop through a list it adds to instead of recursing, but both could
potentially use a good chunk of stack as they are.

Validation sometimes gives several messages when something fails, due to
calls to itself returning errors after reporting their own.  This can be
helpful in hunting down json errors and would be sacrificed if
WJESchemaValidate is refactored to be serial, at least the way I'm
picturing it.  I'm guessing that would be well worth the memory savings,
but I thought I'd better at least mention it.  :^)

I hope you will consider sharing your fork here on github, or posting your
patches and/or custom build scripts; I'm pretty fascinated to see WJE used
this way and I bet others out there would benefit from your modifications
too.  If nothing else, I should at least take your changes for allocation
checking.  :^)

later,
-Owen

**Comment by mkarlesky** [comment]
I'm starting to get some ideas about how to make all this workable. We're
close enough and validation is helpful enough to us that I think it's worth
pressing in a bit more.

Can you give me just a bit more guidance on the serial processing option?
Specifically, what might be the smallest most valuable refactoring we can
do for a worthwhile experiment? A couple sentences or a few lines of pseudo
code will probably suffice. I'm still getting my sea legs inside WJE.

Even if we don't quite succeed with full validation we may yet be able to
build something better than our existing “validation-by-hand” approach.

Happy to share our changes—even if we don't quite fully succeed.

Thanks again. You've both been really helpful and responsive.


On Jun 3, 2016, at 11:01 AM, Owen Swerkstrom <notifications@github.com>
wrote:

There is probably other unchecked allocation code, but schema.c might be
the worst offender. (My bad!) In Netmail we use a custom "slabber" memory
allocator, which is why you'll see everything wrapped and/or macro'd as
Mem* calls. At least that makes them all very easy to find! :^)

If digging into array validation is dying, then my guess is you're right
and there's just no room left on the stack. I am guessing
WJESchemaValidate may yield bigger savings than ListSelectors by having it
loop through a list it adds to instead of recursing, but both could
potentially use a good chunk of stack as they are.

Validation sometimes gives several messages when something fails, due to
calls to itself returning errors after reporting their own. This can be
helpful in hunting down json errors and would be sacrificed if
WJESchemaValidate is refactored to be serial, at least the way I'm
picturing it. I'm guessing that would be well worth the memory savings,
but I thought I'd better at least mention it. :^)

I hope you will consider sharing your fork here on github, or posting your
patches and/or custom build scripts; I'm pretty fascinated to see WJE used
this way and I bet others out there would benefit from your modifications
too. If nothing else, I should at least take your changes for allocation
checking. :^)

later,
-Owen
On Jun 3, 2016 6:47 AM, "Mike Karlesky" <notifications@github.com> wrote:

> Ah yes. The unchecked MemAsprintf() would be fine in pretty much any
> environment larger than ours. I'll see if we can't tighten that up for
more
> graceful failure. Do generic memory allocation (malloc() and its kin)
> generally get checked?
>
> *In the meantime, I have some success to report!*
>
> I've learned that I can, in fact, successfully parse JSON and a schema and
> validate them *if* there are no arrays in the JSON string. To be clear,
> my little setup of nonsense JSON and a simple schema for it parsed
> successfully after I had previously tweaked wjelement buffer allocation.
> However, validation would go off into the weeds. By removing an array (of
> size 1) of simple objects in my testing JSON string, validation now
> succeeds.
>
> So I'm guessing that the array of JSON object (singular—as there was only
> one) is tripping us over into recursion inside validation that is blowing
> up the stack? I should note that the schema only specifies top-level
simple
> key/value pairs at present. I had cut out the specification for the array
> long ago as I tried to isolate the parsing and validation issues early on.
>
> Does this tell us something useful? Thank you again!
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <
https://github.com/netmail-open/wjelement/issues/58#issuecomment-223558629>,
> or mute the thread
> <
https://github.com/notifications/unsubscribe/ABJq04hJJnVHPGt_VxehP_zGmR6zmRGAks5qIBQ-gaJpZM4ItF4h
>
> .
>

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/netmail-open/wjelement/issues/58#issuecomment-223603492>,
or mute the thread
<https://github.com/notifications/unsubscribe/AA__5g-fULjaZRyHePXjwQcPO7TgcvH-ks5qIEHjgaJpZM4ItF4h>
.

**Comment by penduin** [comment]
I was thinking of just setting up a linked list, a quick structure
with WJElement pointers for the document and the schema, and the next
item.  When WJESchemaValidate starts, it would add one item to that
list using what was passed in, and start looping over it.

while(list) {
    document = list->document;
    schema = list->schema;
    /* bulk of WJESchemaValidate */
    tmp = list->next;
    MemRelease(&tmp);
    list = tmp;
}

As it encounters things that require children to be validated, instead
of calling itself with a sub-document and sub-schema, it would build
and add an item to that list (I'd just insert as the next one, why
bother appending :^) and carry on. In some cases it will be adding a
bunch of items due to looping.  This will change the order in which
elements get validated, but we can still bail, clean up, and return
when we encounter an error.

So most of WJESchemaValidate will happen inside a loop, with a little
bit of initialization to get the list going.  And wherever it calls
itself now, it will instead be adding to the list.  Each time through
the loop will process and remove one item.  Where it returns errors
now, it will set an error condition and break out of the loop, after
which the list (if any) will be free'd up.

The same idea should work for ListSelectors.  Does all of that make
sense?  I'd actually take a crack at this myself, but I'm taking off
soon for a very busy weekend of making a short film.  :^)
http://48hourfilm.com

later,
-Owen

**Comment by mkarlesky** [comment]
After doing quite a few experiments, I'm reasonably sure that WJE will work for us. Unfortunately, we just don't have enough RAM.

However, in looking ahead I'm also quite confident we are destined to run out of RAM as we finish building out this project regardless of whether we include WJE.

So after a fair amount of thought, research, and discussion we decided to tackle our memory issue now. We can make that change in relatively short order with an add-on board and a surprisingly small amount of code. The end result will give us way more heap (64k) and free up our current RAM for lots of stack space (8k minus whatever ends up in the DATA section). I intend to make a few more memory handling improvements in WJE, but I think it best to leave its current execution as is. We can go back to exercising it next week after we finish this RAM upgrade.

I'm quite confident we needed to clear this hurdle eventually. The first benefit of WJE may have simply been as motivation for us to get ahead of our RAM issue early. I'll keep you posted.

**Comment by mkarlesky** [comment]
Back on the mic…

Just wanted you to know that we were successful in expanding the amount of memory on our board. With our production code loaded, our available heap is now in the 50+k range and our available stack is in the 3k range.

And… I can now load waaay bigger JSON strings and successfully parse them. That's great. But as soon as I run schema validation against a JSON string that includes any nesting, it appears we pretty much instantly run out of stack.

Now, a consequence of our expanded memory is that we should be able to move our memory map around to give ourselves a full 8k stack. That could certainly help, but it does make me a little nervous. An intriguing set of alternatives is that we have additional banks of RAM at our disposal. We can't combine them into one giant segment of RAM, but we can switch among them for dedicated purposes. That means we could have a 64k byte buffer available just for WJElement. It also means we could have another separate 64k heap available just for WJElement.

Given how WJElement uses the stack at present during validation and given the giant byte buffer and/or the dedicated heap, how might we take advantage of these for WJE to solve this stack issue?

Thanks again!

**Comment by penduin** [comment]
Off the cuff, I think the de-recursion-ization we discussed before will be
the best way to limit stack use, if you'd like to have as much available as
possible for larger documents.  If those two functions are "flattened" then
memory use should be pretty straightforward.  Then it would just be a
matter of finding out how much stack you ever actually need, and giving the
rest to work and buffer space.

If you want to avoid such refractors, I think the best advice I'm qualified
to give is good old trial and error.  We've never had to run WJE or its
schema stuff in such confined spaces, so you're very much the pioneers
here.  As you demonstrated before and with the buffer limits Micah pointed
out, it sounds like you got pretty far with pretty little work RAM.
Starting there and dialing in how to split between work and stack could be
fairly simple if you have a predictable most-complex schema/json, but if
you don't know that up front, I suppose it's better to err on the side of
extra stack.

Sorry I don't really have any more concrete suggestions at the moment.
Micah, does anything else come to mind?

later,
-Owen

**Comment by minego** [comment]
I think you're right. Recursion will eat stack very quickly.

Another simpler option may be to move as much as possible off the stack in
the functions that are used while recursing. If there are any stack buffers
that could be switched to an allocated buffer then that might be enough.
On Jun 11, 2016 10:31 AM, "Owen Swerkstrom" <notifications@github.com>
wrote:

Off the cuff, I think the de-recursion-ization we discussed before will be
the best way to limit stack use, if you'd like to have as much available as
possible for larger documents. If those two functions are "flattened" then
memory use should be pretty straightforward. Then it would just be a
matter of finding out how much stack you ever actually need, and giving the
rest to work and buffer space.

If you want to avoid such refractors, I think the best advice I'm qualified
to give is good old trial and error. We've never had to run WJE or its
schema stuff in such confined spaces, so you're very much the pioneers
here. As you demonstrated before and with the buffer limits Micah pointed
out, it sounds like you got pretty far with pretty little work RAM.
Starting there and dialing in how to split between work and stack could be
fairly simple if you have a predictable most-complex schema/json, but if
you don't know that up front, I suppose it's better to err on the side of
extra stack.

Sorry I don't really have any more concrete suggestions at the moment.
Micah, does anything else come to mind?

later,
-Owen

On Jun 10, 2016 6:09 PM, "Mike Karlesky" <notifications@github.com> wrote:

> Back on the mic…
>
> Just wanted you to know that we were successful in expanding the amount of
> memory on our board. With our production code loaded, our available heap
is
> now in the 50+k range and our available stack is in the 3k range.
>
> And… I can now load waaay bigger JSON strings and successfully parse them.
> That's great. But as soon as I run schema validation against a JSON string
> that includes any nesting, it appears we pretty much instantly run out of
> stack.
>
> Now, a consequence of our expanded memory is that we should be able to
> move our memory map around to give ourselves a full 8k stack. That could
> certainly help, but it does make me a little nervous. An intriguing set of
> alternatives is that we have additional banks of RAM at our disposal. We
> can't combine them into one giant segment of RAM, but we can switch among
> them for dedicated purposes. That means we could have a 64k byte buffer
> available just for WJElement. It also means we could have another separate
> 64k heap available just for WJElement.
>
> Given how WJElement uses the stack at present during validation and given
> the giant byte buffer and/or the dedicated heap, how might we take
> advantage of these for WJE to solve this stack issue?
>
> Thanks again!
>
> —
> You are receiving this because you commented.

> Reply to this email directly, view it on GitHub
> <
https://github.com/netmail-open/wjelement/issues/58#issuecomment-225316761>,
> or mute the thread
> <
https://github.com/notifications/unsubscribe/ABJq0w8BaMkKV5BLeWskmmn9ug5_bdQQks5qKe6XgaJpZM4ItF4h
>
> .
>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/netmail-open/wjelement/issues/58#issuecomment-225373189>,
or mute the thread
<https://github.com/notifications/unsubscribe/AAcoiKYFZaEeda1_fVlH0Ry3OzsiGSRuks5qKuK8gaJpZM4ItF4h>
.

**Comment by mkarlesky** [comment]
Thanks for the thoughts. We need to finish up this expanded RAM work. Once that's in place I'll start playing around with some options to flatten out validation. I'll let you know where we end up.

**Comment by mkarlesky** [comment]
After some detours to other matters, I'm back at it.

I implemented the linked list idea to flatten out the recursion within `SchemaValidate()` as a starting point. I'm running the changes in my local test harness (i.e. on OS X). A schema validation runs, but all I'm seeing is this in an infinite loop:

> (root) is of incorrect type

This message appears in a loop regardless of whether schema validation should pass or fail.

I gather, then, that I likely haven't screwed up my pointers and list operations enough to crash. But, clearly, something is amiss.

I wasn't sure how to handle the following:

1. The recursion statements in the setup code before the while loop at `schema.c:548`. I wondered if these steps might require special treatment.
1. Error states, breaks, and returning failures. I've added nothing to this effect. And, in fact, in removing some of the recursion calls I also had to remove error handling because those code blocks depended on a failure return code from `SchemaValidate()`.
1. The loop `while((memb = WJEGet(list->schema, "[]", memb))) {...}`. Should this continue to be a while loop that is then nested within my list iterating while loop? Or should my list handling loop somehow take over some of this existing while loop's responsibilities?

I've attached my changed files. Any ideas on how to track down the problem and properly address the above issues?

[WJElement Changes.zip](https://github.com/netmail-open/wjelement/files/364890/WJElement.Changes.zip)

**Comment by mkarlesky** [comment]
I was able to flatten out `SchemaValidate()` using the linked list approach. There were a handful of problems to resolve along the way (since my last message). One of the key problems was that I misinterpreted the remark about how to add to the linked list and did not engage my brain until later. The order of the list I initially created caused an infinite loop.

I haven't yet tried the new flattened WJElement on our board. I still have to flatten out `ListSelectors()`. And there's a couple niggling outstanding issues.

The biggest remaining questions are:

1. What's the right way to handle the recursion calls towards the very beginning of `SchemaValidate()`? Can I just add to the linked list to handle `definitions`, `extends`, etc. before entering the linked list processing loop?
1. How shall I handle error conditions? I have to admit that I don't quite follow the `fail` and `anyFail` scheme. Consequently, I'm uncertain where to flag a failure and when to break out of the loop in the new arrangement. Guidance is appreciated.

Getting close. Once `ListSelectors()` is flattened out and some of these other issues are addressed I can try the new stack-conserving version of WJElement on our board.

**Comment by mkarlesky** [comment]
Another update. **WJElement works just fine on our AVR ATmega2560 *with recursion*!** I have WJElement running validation of a JSON blob against a suitably complex schema on our board. I did, of course, include the few small changes I made early on to get it to build and link for our platform. Otherwise, WJElement is nearly the original code as provided through github.

The problem has to do with `asprintf()`. Our platform's `stdlib` does not implement it. So the build for our board relies on the replacement implementation of `asprintf()` in `xpl.c`. There's some kind of pointer dereferencing issue in there related to `*ret`. I don't yet understand the problem, but I was able to narrow in on it and work around it. I still need to dig into the problem further. Oddly, if I force the `asprintf()` code in `xpl.c` to be used in a native OS X build everything works fine. It's quite perplexing.

The reason validation blew up in my test cases on our board was specific to validating arrays. It wasn't due to the depth of recursion. Instead, it was because the test JSON and schema I wrote only cause `MemAsprintf()` to be called in relation to array handling. No other code that calls `MemAsprintf()` was exercised by my test case.

**Comment by mkarlesky** [comment]
Issues resolved. Apart from my small initial changes, the core of WJElement including schema validation is now working on an embedded system.

The problem was not recursion at all but rather issues with the provided implementation of `asprintf()` in `xpl.c` given that our platform does not have `asprintf()` available natively. The key problem was the lack of a prototype of `asprintf()` in `xpl.h`. This messed with the handling of the var args in the calls to `asprintf()` and corrupted the results of `vsnprintf()` calls. Adding a prototype for `asprintf()` within an `#ifndef asprintf` block fixed the crash.

I also made some improvements to `asprintf()` in `xpl.c`. The state of `va_list` after use is undefined. The most portable (safest) way to process var args twice in the same function is to make use of the `va_copy` macro. Below is an improved replacement implementation of `asprintf()`.

```
#ifndef asprintf
EXPORT int asprintf(char **ret, const char *fmt, ...) {
  va_list ap1;
  va_list ap2;
  int count;

  va_start(ap1, fmt);
  va_copy(ap2, ap1);
  count = vsnprintf(NULL, 0, fmt, ap1);
  va_end(ap1);

  if(count > 0) {
    char* buffer;

    if (!(buffer = (char*)malloc(count+1))) {
      va_end(ap2);
      return -1;
    }
    count = vsnprintf(buffer, count+1, fmt, ap2);
    *ret = buffer;
  }
  va_end(ap2);
  return count;
}
#endif
```
