### ISSUE TITLE
Resource Leaks in the example code

### ISSUE THREAD

**Issue by saadmunir90** [netmail-open/wjelement#98]
We have included this lib in our code. We run the CPPCheck for static code analysis on the whole code base which reported two resource leaks in the example. Although this is harmless but if fixed in source code would allow a clean CPPCheck run.

`
<error id="resourceLeak" severity="error" msg="Resource leak: jsonfile" verbose="Resource leak: jsonfile" cwe="775">
<location file=".../wjelement/example/validate.c" line="96" column="3"/>
<symbol>jsonfile</symbol>
</error>
`

`
<error id="resourceLeak" severity="error" msg="Resource leak: schemafile" verbose="Resource leak: schemafile" cwe="775">
<location file=".../wjelement/example/validate.c" line="107" column="3"/>
<symbol>schemafile</symbol>
</error> 
`

I have fixed the issue and here is the link to diff file.
https://drive.google.com/file/d/1X5cjnV1KjUU5rY6O4-L7CYG9WIg2ZOdR/view?usp=sharing

**Comment by penduin** [comment]
Thank you and good catch!  I'll roll that in soon.

later,
-Owen

On Jan 4, 2021 18:08, "saadmunir90" <notifications@github.com> wrote:

We have included this lib in our code. We run the CPPCheck for static code
analysis on the whole code base which reported two resource leaks in the
example. Although this is harmless but if fixed in source code would allow
a clean CPPCheck run.
jsonfile schemafile

I have fixed the issue and here is the diff.

`
diff --git a/example/validate.c b/example/validate.c
index 8e8dab0..a85168b 100644
--- a/example/validate.c
+++ b/example/validate.c
@@ -78,6 +78,7 @@ int main(int argc, char **argv) {
WJElement json;
WJElement schema;
char *format;

   -

   int ret_value = 0;

   if(argc != 3 && argc != 4) {
   printf("usage:\n");
   @@ -89,11 +90,13 @@ int main(int argc, char **argv) {

   if(!(jsonfile = fopen(argv[1], "r"))) {
   fprintf(stderr, "json file not found: '%s'\n", argv[1]);


   -

     return 1;



   -

     ret_value = 1;

   -

     goto ret;

   }
   if(!(schemafile = fopen(argv[2], "r"))) {
   fprintf(stderr, "schema file not found: '%s'\n", argv[2]);


   -

     return 2;



   -

     ret_value = 2;

   -

     goto ret;

   }
   if(argc == 4) {
   format = argv[3];
   @@ -104,13 +107,14 @@ int main(int argc, char **argv) {
   if(!(readjson = WJROpenFILEDocument(jsonfile, NULL, 0)) ||
   !(json = WJEOpenDocument(readjson, NULL, NULL, NULL))) {
   fprintf(stderr, "json could not be read.\n");


   -

     return 3;



   -

     ret_value = 3;

   -

     goto ret;

   }
   if(!(readschema = WJROpenFILEDocument(schemafile, NULL, 0)) ||
   !(schema = WJEOpenDocument(readschema, NULL, NULL, NULL))) {
   fprintf(stderr, "schema could not be read.\n");


   -

     WJECloseDocument(json);

   -

     return 4;



   -

     ret_value = 4;

   -

     goto ret;

   }

   WJEDump(json);
   @@ -125,11 +129,12 @@ int main(int argc, char **argv) {
   printf("validation: FAIL\n");
   }


   - WJECloseDocument(json);
   - WJECloseDocument(schema);
   - WJRCloseDocument(readjson);
   - WJRCloseDocument(readschema);
   - fclose(jsonfile);
   - fclose(schemafile);
   - return 0;


   - ret:
   -

     if(json) WJECloseDocument(json);

   -

     if(schema) WJECloseDocument(schema);

   -

     if(readjson) WJRCloseDocument(readjson);

   -

     if(readschema) WJRCloseDocument(readschema);

   -

     if(jsonfile) fclose(jsonfile);

   -

     if(schemafile) fclose(schemafile);

   -

     return ret_value;


}
`

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/netmail-open/wjelement/issues/98>, or unsubscribe

**Comment by penduin** [comment]
fixed the validate example not to leak (without goto's, but same idea)
thanks @saadmunir90 !
